### ISSUE TITLE
Improve Mobile UI

### ISSUE THREAD

**Issue by Hacksore** [The-Enthusiast-404/git-begin#32]
Many people scour the “good first issue” label.

you should add a few random ones to your site maybe here?
![IMG_2748](https://github.com/user-attachments/assets/003b35d3-f8e5-4ca9-a9ed-842cdffcd58c)

**Comment by dotslashbit** [comment]
All of the issues that we show are good first issues

**Comment by Hacksore** [comment]
Yeah I was on mobile and couldn't tell cause you to scroll past a massive search form.

Would make sense to pill the labels like github does and having a more minimized default search experience for mobile. 
![image](https://github.com/user-attachments/assets/74d840b2-57df-4ca2-a3c2-f35b1cbdb294)

![image](https://github.com/user-attachments/assets/38bf0770-10bc-4f07-8198-2204433e404c)

**Comment by dotslashbit** [comment]
Yeah I'll update the mobile UI, thanks for informing me about it. I really appreciate it 🙏

**Comment by dotslashbit** [comment]
Improve the mobile UI, specifically the search filter appearance as its covering the entire view, instead make the issues visible from the start.

**Comment by Sechorda** [comment]
I would like to work on the issue of the mobile UI. Have you done anything on this yet @dotslashbit?

Thanks.

**Comment by dotslashbit** [comment]
@Sechorda Hi, please feel free to work on this. I haven't worked on it. Just let me know if you are working on it or not, if yes then I'll assign it to you.

I'll always be thankful to you for your contribution 😊

**Comment by Sechorda** [comment]
@dotslashbit I'll take this one!
