### ISSUE TITLE
No Dockerfile is present in the codebase

### ISSUE THREAD

**Issue by sahitya-chandra** [The-Enthusiast-404/git-begin#33]
Dockerfile must be added in the repo. so that setting project locally could become easy.

**Comment by sahitya-chandra** [comment]
Can you assign this issue to me.

**Comment by dotslashbit** [comment]
@sahitya-chandra  I appreciate your enthusiasm to contribute to this project but I don't think there's any need to add docker to this. Its already a pretty straight forward setup.

If you want to work on something else, then do let me know we can find out some issues to work on

**Comment by sahitya-chandra** [comment]
Yes sure i am interested, if there is any issue then plzz let me know

**Comment by dotslashbit** [comment]
@sahitya-chandra We have a categories filter and there are now may be 7 categories, I want to include even more categories. Even if you don't want to work on it, please create a issue about it (creating issues are also a part of contributing)

Another thing is we currently don't have multi language support for language filter i.e. you can only choose python or javaascript or java and so on. You can't choose multiple languages at once for language filter. Please create an issue on it, and feel free to work on it 

Both of them are high impact features (take your time).Just create those issues first and then we can discuss there. After creating the issues, I'll close this issue.
