### ISSUE TITLE
Add more filter categories/options to get more precise results

### ISSUE THREAD

**Issue by sahitya-chandra** [The-Enthusiast-404/git-begin#34]
More filters needed for exact and accurate results

**Comment by dotslashbit** [comment]
@sahitya-chandra Specifically, you only need to add more categories on the filter
<img width="412" alt="Screenshot 2024-08-24 at 23 13 45" src="https://github.com/user-attachments/assets/cea00aa6-8222-45a6-8333-0b63b451234c">

**Comment by sahitya-chandra** [comment]
@dotslashbit So i need to add more option to this accordian only.

**Comment by dotslashbit** [comment]
Yes

**Comment by sahitya-chandra** [comment]
and can you tell me where can i find my github api key so that i can set it up locally

**Comment by sahitya-chandra** [comment]
can you tell me specifically what more categories should i add

**Comment by dotslashbit** [comment]
@sahitya-chandra sure I can help you with that. 

Here's where you can get your API key --> https://github.com/settings/tokens

Create the classic token

**Comment by dotslashbit** [comment]
We are fetching the categories from the tags 
<img width="412" alt="Screenshot 2024-08-24 at 23 27 37" src="https://github.com/user-attachments/assets/6bee923f-e091-433f-94b6-12ee8769ae85">

You can add categories like data visualization, data analytics, operating system, browser, etc.

Just do one thing, after adding each category, always check if the category is working correctly or not. First check if issues are being fetched or not, then click on some of the issues to check if the tag is available on those repos or not

If you need any help just let me know.

I appreciate your contributions
