### ISSUE TITLE
Add a filter for number of forks

### ISSUE THREAD

**Issue by dotslashbit** [The-Enthusiast-404/git-begin#37]
We need to add another filter in the filter form, that'll allow users to choose minimum number of forks a repo should have

**Comment by dotslashbit** [comment]
@pamarthiabhinav do you want to work on it?

**Comment by pamarthiabhinav** [comment]
Let me see if I can do that 🤔

**Comment by dotslashbit** [comment]
I would say go for it, open a draft PR and then let me know if you are stuck, we can figure it out. How about that?

**Comment by pamarthiabhinav** [comment]
Sure @dotslashbit, That sounds great 👍

**Comment by dotslashbit** [comment]
Awesome, just link a PR to this issue and ping me in the PR if you need anything, I'm assigning this to you
