### ISSUE TITLE
Update Github API query

### ISSUE THREAD

**Issue by dotslashbit** [The-Enthusiast-404/git-begin#49]
Currently the api query fetches issues with closed PRs only when hasPR is checked. We need to update the query so that it'll fetch:
- All issues without PRs and closed PRs (when hasPR is false)
- All issues with open PRs or draft PRs (when hasPR is true)

If you want to work on this, please comment below. If you need any help, just ping me, I can help you with this, thanks

**Comment by sanketmn26** [comment]
Checked response data. It is fetching data for has_pull_request = true/false both.

![Screenshot (226)](https://github.com/user-attachments/assets/4977f950-f9a2-4038-a77d-d01c780d8901)

**Comment by dotslashbit** [comment]
Yes but what we want to know is whether it's a open pr or draft or close

**Comment by Sechorda** [comment]
@dotslashbit @sanketmn26 I was able to retrieve the PR state from the graphql query. Are you currently working on this? I May submit a PR here shortly.

![image](https://github.com/user-attachments/assets/5c681aa7-0fb3-4843-af0b-c6253a919dc5)

**Comment by dotslashbit** [comment]
@sanketmn26 @Sechorda 

We are using graphql queries and in the docs I found this --> https://docs.github.com/en/graphql/reference/objects#pullrequest

It basically says that every Pr has a closed boolean, so intuitively what I'm thinking is,
lets keep the existing queries as is.
After fetching all the issues , we can run a query by providing the the Pr object and check its closed value if its closed then we can count it as the issue associated with the current Pr doesn't have any PRs.

Do you get it?  If you have any other idea, do let me know

We can take time on this, its not that big of a deal but this will make sure we are giving the best results possible to the user

**Comment by Sechorda** [comment]
@dotslashbit I think I know what you mean, but don't exactly follow. My brain went this way:

Include the PR state in the query, resulting in still only one query.
Filter issues base on PR state status with the logic that if it's open, draft, closed, or null (saw some null edge cases) then it returns the issue to the user.

`const filteredIssues = issues.filter(issue => {
      if (!params.hasPullRequests) {
        return !issue.has_pull_requests;
      } else {
        return issue.has_pull_requests && 
               (issue.pr_status === 'OPEN' || 
                issue.pr_status === 'DRAFT' || 
                issue.pr_status === 'CLOSED' || 
                issue.pr_status === null);
      }
    });`

**Comment by dotslashbit** [comment]
@Sechorda I get it, but is the query working? If it's working then your way is a better solution

**Comment by Sechorda** [comment]
@dotslashbit the PR draft I submitted has a working query and filter based on the requested PR state logic. Double check me though!

**Comment by dotslashbit** [comment]
@Sechorda sure will do that later, thank you so much

**Comment by Sechorda** [comment]
@dotslashbit woot

**Comment by sanketmn26** [comment]
@dotslashbit @Sechorda  There was a bug in below statement.

![Screenshot (227)](https://github.com/user-attachments/assets/825f9c87-113a-42b1-8519-21282e11f8f8)


We were not importing "nodes" data in query. So when "timelineItems.totalCount > 0 === true". It was throwing error because It could not find "totalCount.nodes"

![Screenshot (228)](https://github.com/user-attachments/assets/f9064041-d97f-4cfa-b1fc-d7d1a214953f)

Please have a look.

**Comment by dotslashbit** [comment]
@sanketmn26 are you getting an error in the web app or in dev mode. Also have you updated your local setup

**Comment by sanketmn26** [comment]
@dotslashbit I was getting error in dev mode in local setup. But not after adding nodes in query.

![Screenshot (229)](https://github.com/user-attachments/assets/cf99c1f5-9fad-48e7-b9aa-5f285befe0c0)

**Comment by dotslashbit** [comment]
@sanketmn26 update your local code, cause I checked on my laptop and it's working perfectly fine
