### ISSUE TITLE
Mobile UI search bar functionality

### ISSUE THREAD

**Issue by Sechorda** [The-Enthusiast-404/git-begin#53]
While implementing the mobile UI, I added a search bar to accompany the pill dropdown menu, as it seemed like the most intuitive way to design the mobile layout.

The search bar doesn't currently return valid searches from the backend, any search query will only poll the filtered parameters that already existed.

Please assign me to get a working search bar for keywords in the mobile UI.

ty

**Comment by dotslashbit** [comment]
Assigned
