### ISSUE TITLE
Cleanup default URL parameters on initial visit

### ISSUE THREAD

**Issue by Sechorda** [The-Enthusiast-404/git-begin#54]
I noticed that the URL parameters are all included in the initial landing of the page.

![image](https://github.com/user-attachments/assets/111f16d1-1a65-4fac-8bc8-f1b192b37979)

We could clean this up until the user specifies non-default filters. 

Feel free to assign me

**Comment by dotslashbit** [comment]
I would say let's label it good first issues and let someone new handle it. You already have a lot on your hands. If you can, then please help the contributor by reviewing it 

What do you think?

**Comment by Sechorda** [comment]
@dotslashbit sounds good.

ty

**Comment by dotslashbit** [comment]
Note to someone who wants to contribute to this:
> If you want to contribute, just comment down below and then after I assign you start working on it. @Sechorda will be there to help you if you get stuck

**Comment by gsriram24** [comment]
This seems like an easy fix. Please assign this to me. I can work on this.

**Comment by dotslashbit** [comment]
@gsriram24 sure go ahead

**Comment by gsriram24** [comment]
https://github.com/The-Enthusiast-404/git-begin/pull/85

Have created a PR, please check
