### ISSUE TITLE
Multi Select language filter looks bad

### ISSUE THREAD

**Issue by dotslashbit** [The-Enthusiast-404/git-begin#59]
<img width="1822" alt="Screenshot 2024-08-30 at 09 11 28" src="https://github.com/user-attachments/assets/99b576e9-cf8f-4d06-a5d2-1c225628d3f7">

The problem is the extra space the placeholder is taking. I think we should only show placeholder whenever there's no language selected

**Comment by ST-KO** [comment]
Hi @dotslashbit I can work on that.

**Comment by dotslashbit** [comment]
Please go ahead
