### ISSUE TITLE
Update the Github Icon on the Header

### ISSUE THREAD

**Issue by dotslashbit** [The-Enthusiast-404/git-begin#61]
<img width="1822" alt="Screenshot 2024-08-30 at 10 22 26" src="https://github.com/user-attachments/assets/eebe5ccb-a225-4a78-8ee9-06fa5e01957e">

We want the github icon to be similar to what hugo website has.

If you want to work on it, just comment down below

If you got stuck, me and other constributors are here to help, please feel free to reach out to anyone

**Comment by enriqueqs** [comment]
I am creating a PR

**Comment by dotslashbit** [comment]
@enriqueqs sure go ahead
