### ISSUE TITLE
Add meta description to the web app

### ISSUE THREAD

**Issue by dotslashbit** [The-Enthusiast-404/git-begin#63]
In the lighthouse report, I noticed that we don't have meta description for the web app

<img width="785" alt="Screenshot 2024-08-30 at 16 43 15" src="https://github.com/user-attachments/assets/3bf805c1-602c-466b-881f-cfbde6bac1c3">

If you want to work on it, then let me know in the comments, then I'll give you what to write

If you got stuck, me and other contributors are here to help

**Comment by rodriveiga01** [comment]
Hello I want to contribute in this issue. If you could please tell me what to write I do it

**Comment by rodriveiga01** [comment]
I could do that. Please tell me what to write

**Comment by dotslashbit** [comment]
Please go ahead

**Comment by dotslashbit** [comment]
This is what to write:

Start contributing to open source projects by finding good first issues
