### ISSUE TITLE
Update Footer text position

### ISSUE THREAD

**Issue by dotslashbit** [The-Enthusiast-404/git-begin#70]
<img width="1822" alt="Screenshot 2024-09-01 at 20 33 57" src="https://github.com/user-attachments/assets/7a6cfab7-5c86-47f5-b8b9-d7527d937654">

Keep everything centered.
Put the texts from left to the center.
Then below these texts put the icons

If you want to contribute, please comment down below.
If you get stuck, then please reach out to me or any contributors, we are here to help 😊

**Comment by rodriveiga01** [comment]
I will work on that
