### ISSUE TITLE
Create desktop search bar

### ISSUE THREAD

**Issue by Sechorda** [The-Enthusiast-404/git-begin#71]
This issue is to implement a desktop search bar much like mobile.

The goal of this feature is to be able to search via keywords, but most importantly repository names.

@dotslashbit Where should we put this search bar? Above the returned scrolling list, or on the left sidebar with the filters?

**Comment by rodriveiga01** [comment]
I think that it would align great if it was above the returned scrolling list but not the full width, just the width of the list container. If it was implement the functionality would be the same as the mobile version or not?

**Comment by dotslashbit** [comment]
@Sechorda I think it would be neat to have it on the left, cause all the filtration are done on that side and this is also one kind of filtration

**Comment by Sechorda** [comment]
@dotslashbit Yeah, I'm thinking a simple filter for repo names and keywords.

**Comment by Sechorda** [comment]
update: actively working on this issue!

ty

**Comment by dotslashbit** [comment]
@Sechorda thanks for the update

**Comment by Sechorda** [comment]
@dotslashbit I was working on this for a bit, and I came to the conclusion that this may not add any value to the project or user experience:

keyword search isn't the easiest to implement, and doesn't typically return useful results.
Searching for a repository name doesn't feel useful to me as this platform is to explore repository agnostic good first issues.

thoughts on closing this one and rethinking the mobile UI to remove the search bar?

**Comment by dotslashbit** [comment]
@Sechorda Yeah you're right, we should also remove the mobile search bar too. It'll be great if you can create another issue and remove that
