### ISSUE TITLE
Implement Multi-Language Support for the Website

### ISSUE THREAD

**Issue by rodriveiga01** [The-Enthusiast-404/git-begin#72]
## Description

The website is currently available only in English, which can be a barrier for developers who are not fluent in the language. To make the website more accessible, I propose adding a feature that allows users to select their preferred language via a button, dropdown menu, or another selection method.

## Proposed Solution

I suggest implementing this feature using the [i18n framework](https://www.i18next.com/), which leverages a collection of JSON files for different languages. Each language would have its own JSON file, and the website would automatically translate based on the user’s selection.

Additionally, we could consider implementing automatic language detection based on the user's location. However, it might be preferable to give users the option to enable or disable this feature.

## Contribution:

I'm willing to work on this feature if approved.

**Comment by dotslashbit** [comment]
@rodriveiga01 sure go for it, it'll enhance the accessibility greatly

**Comment by rodriveiga01** [comment]
Just need to know what languages should I put. Maybe if there's a lot I should put all of them in one file. Let me know what languages do you want the website to be translated

**Comment by rodriveiga01** [comment]
In the meanwhile I will start to implement the logic

**Comment by dotslashbit** [comment]
@rodriveiga01 At first just implement whatever you are comfortable with, after that we can discuss what other languages to include
