### ISSUE TITLE
Fix for Non-Scrollable Options in Dropdown Menu

### ISSUE THREAD

**Issue by Syed-Bilal-Haider-Engineer** [The-Enthusiast-404/git-begin#81]
I found an open-source repo, but I'm having an issue selecting options. The options are not scrollable, so not all of them are visible on the screen. When I scroll the webpage and reach the same height as the options, they become visible. If more options are added in the future, this will create a problem. The solution is to make the possibilities scrollable. Categories should be scrollable similar to language input scroll.

Watch the complete video. 
https://github.com/user-attachments/assets/d69f8272-ac31-414c-b971-540b30611ff1

![WhatsApp Image 2024-09-06 at 16 01 13](https://github.com/user-attachments/assets/ff673759-8cce-4f0b-ad38-c361878141e4)

![WhatsApp Image 2024-09-06 at 16 00 44](https://github.com/user-attachments/assets/83227f7a-8fcc-4a89-9d1d-bea9a6de9f90)

**Comment by Syed-Bilal-Haider-Engineer** [comment]
Please assign me, I'm fixing it. thanks

**Comment by dotslashbit** [comment]
Ok go ahead

**Comment by Syed-Bilal-Haider-Engineer** [comment]
Please add me as a contributor, which is helpful for me, I wanna more contributions. thanks

**Comment by dotslashbit** [comment]
@Syed-Bilal-Haider-Engineer GitHub will add you automatically, anyone who contributes and merges atleast 1pr becomes a contributor
